<p>Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:</p>
<table><tr><td>Triangle</td>
<td> </td>
<td>P<sub>3,<i>n</i></sub>=<i>n</i>(<i>n</i>+1)/2</td>
<td> </td>
<td>1, 3, 6, 10, 15, ...</td>
</tr><tr><td>Square</td>
<td> </td>
<td>P<sub>4,<i>n</i></sub>=<i>n</i><sup>2</sup></td>
<td> </td>
<td>1, 4, 9, 16, 25, ...</td>
</tr><tr><td>Pentagonal</td>
<td> </td>
<td>P<sub>5,<i>n</i></sub>=<i>n</i>(3<i>n</i>−1)/2</td>
<td> </td>
<td>1, 5, 12, 22, 35, ...</td>
</tr><tr><td>Hexagonal</td>
<td> </td>
<td>P<sub>6,<i>n</i></sub>=<i>n</i>(2<i>n</i>−1)</td>
<td> </td>
<td>1, 6, 15, 28, 45, ...</td>
</tr><tr><td>Heptagonal</td>
<td> </td>
<td>P<sub>7,<i>n</i></sub>=<i>n</i>(5<i>n</i>−3)/2</td>
<td> </td>
<td>1, 7, 18, 34, 55, ...</td>
</tr><tr><td>Octagonal</td>
<td> </td>
<td>P<sub>8,<i>n</i></sub>=<i>n</i>(3<i>n</i>−2)</td>
<td> </td>
<td>1, 8, 21, 40, 65, ...</td>
</tr></table><p>The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.</p>
<ol><li>The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).</li>
<li>Each polygonal type: triangle (P<sub>3,127</sub>=8128), square (P<sub>4,91</sub>=8281), and pentagonal (P<sub>5,44</sub>=2882), is represented by a different number in the set.</li>
<li>This is the only set of 4-digit numbers with this property.</li>
</ol><p>Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.</p>

In [41]:
from collections import defaultdict

In [42]:
lambdas = {
    3: lambda n: n*(n+1)//2,
    4: lambda n: n*n,
    5: lambda n: n*(3*n-1)//2,
    6: lambda n: n*(2*n-1),
    7: lambda n: n*(5*n-3)//2,
    8: lambda n: n*(3*n-2)
}

In [61]:
nums = defaultdict(list)
total = set()
def gen():
    i = 1
    while True:
        for j in range(3, 9):
            num = lambdas[j](i)
            if j == 3 and len(str(num)) == 5:
                return
            if len(str(num)) == 4:
                nums[j].append([num, i])
                total.add((num, i, j))
        i += 1

In [62]:
gen()

In [65]:
list(total)[0]

(3201, 33, 8)

In [66]:
def bar():
    cyclic = lambda a, b : a[0] % 100 == b[0] // 100
    diff = lambda arr, i: all([a[1] != i[1] and a[2] != i[2] for a in arr])

    for a in total:
        for b in total:
            if diff([a], b) and cyclic(a, b):
                for c in total:
                    if diff([a, b], c) and cyclic(b, c):
                        for d in total:
                            if diff([a, b, c], d) and cyclic(c, d):
                                for e in total:
                                    if diff([a, b, c, d], e) and cyclic(d, e):
                                        for f in total:
                                            if diff([a,b,c,d,e], f) and cyclic(e, f) and cyclic(f, a):
                                                return [a,b,c,d,e,f]

In [68]:
res = bar()

In [70]:
res

[(8256, 128, 3),
 (5625, 75, 4),
 (2512, 32, 7),
 (1281, 21, 8),
 (8128, 64, 6),
 (2882, 44, 5)]

In [69]:
sum([n[0] for n in res])

28684